"""group and is_admin

Revision ID: dc629a3cf719
Revises: 727ca25ba722
Create Date: 2024-10-01 14:52:00.632043

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "dc629a3cf719"
down_revision: Union[str, None] = "727ca25ba722"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("group", sa.Integer(), nullable=True))
    op.add_column(
        "users",
        sa.Column(
            "is_admin", sa.Boolean(), server_default="False", nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "is_admin")
    op.drop_column("users", "group")
    # ### end Alembic commands ###
